Linux_SFML:
	g++ -Wall -ansi -pedantic main.cpp -o main -lsfml-graphics -lsfml-window -lsfml-system && ./main
mac:
	g++ -Wall -ansi -pedantic main.cpp -o main -I/opt/homebrew/include -L/opt/homebrew/lib -lsfml-graphics -lsfml-window -lsfml-system && ./main
